<?php
/**
 * @category    Mxperts
 * @package     Mxperts_Invoice
 * @authors     TMEDIA cross communications <info@tmedia.de>, Johannes Teitge <teitge@tmedia.de>, Daniel Sasse <d.sasse1984@googlemail.com>
 * @copyright   TMEDIA cross communications, Doris Teitge-Seifert
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<p>
    <?php echo $this->getMethod()->getTitle() ?><br />
    <?php if ($this->getMethod()->getInfoText('infotext_overview')): ?>
        <?php echo $this->getMethod()->getInfoText('infotext_overview') ?><br />
    <?php endif; ?>
</p>